"""Accounts: invite, verify, password, reset (auth arc S3).

Adding a person IS creating a user. The properties pinned here are the ones
that would be quietly wrong for months otherwise:

  1. **A link is single-use and expires.** A reset link that stays live in a
     mailbox is a spare key under the mat.
  2. **Setting a password kills every other outstanding link.** Otherwise an
     old invite still sitting in a forwarded email survives the password
     change it was supposed to be replaced by.
  3. **Nothing leaks whether an address exists.** Both the login failure and
     the forgot-password response are identical either way, because whether a
     given address is on this family's account is not a stranger's to test.
  4. **Hashes never reach a surface.** `_public_member` is the one chokepoint,
     and a hash that leaks once is offline-crackable forever.
  5. **Mail is never a hard dependency** — no sender configured still produces
     a working link.

Run from chauffeur/:  python tests/test_accounts.py
"""
import time

from harness import check  # noqa: F401  (isolates CHAUFFEUR_DATA_DIR)

from services import storage, mailer


def _member(name='Vovo', role='parent', email=None):
    """`add_member` returns the TinyDB doc id, not the member id — the app's
    ids are generated by the schema, so the test supplies one."""
    import uuid
    mid = uuid.uuid4().hex
    storage.add_member({'id': mid, 'name': name, 'role': role, 'email': email})
    return mid


def scenario_a_a_link_is_single_use():
    m = _member('Single')
    token = storage.create_auth_link(m, 'invite')
    check(storage.peek_auth_link(token) is not None,
          "a fresh link did not read as valid")
    check(storage.consume_auth_link(token) is not None,
          "a fresh link could not be spent")
    check(storage.consume_auth_link(token) is None,
          "a spent link was accepted a second time — that is a spare key")
    check(storage.peek_auth_link(token) is None,
          "a spent link still peeks as valid")


def scenario_b_a_link_expires():
    m = _member('Expiry')
    token = storage.create_auth_link(m, 'reset', ttl_hours=0)
    # ttl 0 means already expired; no sleeping in tests.
    check(storage.peek_auth_link(token) is None,
          "an expired link was still accepted")


def scenario_c_setting_a_password_kills_the_other_links():
    """The forwarded-invite problem: an old link must not outlive the password
    it was meant to create."""
    m = _member('Twice')
    first = storage.create_auth_link(m, 'invite')
    second = storage.create_auth_link(m, 'invite')
    storage.consume_auth_link(second)
    storage.set_member_password(m, 'correct horse battery')
    storage.invalidate_auth_links(m)
    check(storage.peek_auth_link(first) is None,
          "an earlier invite survived the password being set")


def scenario_d_passwords_verify_and_do_not_leak():
    m = _member('Hashy')
    storage.set_member_password(m, 'correct horse battery')
    check(storage.verify_member_password(m, 'correct horse battery'),
          "the right password was rejected")
    check(not storage.verify_member_password(m, 'wrong horse battery'),
          "the wrong password was accepted")
    check(not storage.verify_member_password(m, ''),
          "an empty password was accepted")
    # The chokepoint. If this ever regresses, a hash is on a kiosk.
    import main
    pub = main._public_member(storage.get_member(m))
    for field in ('password_hash', 'password_salt', 'pin_hash', 'pin_salt'):
        check(field not in pub, f"{field} leaked through _public_member")
    check(pub.get('has_password') is True,
          "has_password is how a surface asks; it was not set")


def scenario_e_a_member_with_no_password_is_not_almost_signed_in():
    """Absence of a credential must never read as a match — the classic
    empty-hash-equals-empty-input bug."""
    m = _member('Nopass')
    check(not storage.verify_member_password(m, ''),
          "a member with no password verified against an empty string")
    check(not storage.verify_member_password(m, 'anything'),
          "a member with no password verified against a guess")


def scenario_f_email_lookup_is_case_insensitive():
    _member('Casey', email='Casey.Jones@Example.COM')
    check(storage.get_member_by_email('casey.jones@example.com') is not None,
          "an address typed in a different case did not find the account")
    check(storage.get_member_by_email('  CASEY.JONES@EXAMPLE.COM  ') is not None,
          "surrounding whitespace defeated the lookup")
    check(storage.get_member_by_email('nobody@example.com') is None,
          "an unknown address matched somebody")


def scenario_g_mail_is_never_a_hard_dependency():
    """No sender configured is a normal state, not an error: the invite still
    produces a link a parent can hand over."""
    check(not mailer.configured({}),
          "an empty settings dict read as a configured mail sender")
    out = mailer.send('someone@example.com', 'Subject', 'Body', settings={})
    check(out['sent'] is False and out['reason'],
          f"an unconfigured send did not report why: {out}")
    # And it never raises — the caller's fallback is better than a 500.
    out = mailer.send('not-an-address', 'Subject', 'Body', settings={})
    check(out['sent'] is False, "an invalid address did not fail softly")


def scenario_h_the_reuse_toggle_mirrors_intake_rather_than_copying():
    """`smtp_use_intake` must READ intake's values, not have copied them at
    save time — a copy fossilises a password the family later changes in one
    place and not the other."""
    settings = {'smtp_use_intake': True, 'ingest_email_host': 'imap.gmail.com',
                'ingest_email_user': 'family@gmail.com',
                'ingest_email_password': 'app-pw'}
    cfg = mailer.config(settings)
    check(cfg['user'] == 'family@gmail.com' and cfg['password'] == 'app-pw',
          f"the toggle did not mirror the intake credentials: {cfg}")
    check(cfg['host'] == 'smtp.gmail.com',
          f"the IMAP host was not translated for sending: {cfg['host']}")
    check(cfg['from'] == 'family@gmail.com',
          "reuse should send as the intake address itself")
    # Changing intake's password changes the sender's, with no second save.
    settings['ingest_email_password'] = 'new-pw'
    check(mailer.config(settings)['password'] == 'new-pw',
          "the mirror had gone stale — it copied instead of reading")


def scenario_i_a_from_address_the_account_does_not_own_is_flagged():
    """Said in the form, because the failure is otherwise a silent bounce."""
    warn = mailer.from_address_warning(
        {'smtp_user': 'family@gmail.com', 'smtp_from': 'noreply@example.com'})
    check(warn and 'reject' in warn,
          f"a mismatched From address was not flagged: {warn}")
    check(mailer.from_address_warning(
        {'smtp_user': 'family@gmail.com', 'smtp_from': 'family@gmail.com'}) is None,
        "a matching From address was flagged anyway")


# --- S4: the admin surface gets an identity ---------------------------------

def scenario_j_ingress_headers_are_only_believed_off_the_tunnel():
    """The trap this avoids is worse than the hole being closed: `X-Hass-Is-
    Admin` is trivially forged, so believing it on a tunnelled request would
    hand the household to anyone who read the source."""
    from services import auth
    ingress = {'x-ingress-path': '/api/hassio_ingress/abc', 'x-hass-is-admin': 'true'}
    check(auth.arrived_via_ingress(ingress),
          "a genuine ingress request was not recognised")
    check(auth.ingress_is_admin(ingress), "an HA admin was not recognised")

    forged = dict(ingress)
    forged['cf-connecting-ip'] = '203.0.113.7'      # came through cloudflared
    check(not auth.arrived_via_ingress(forged),
          "FORGED ingress headers were believed on a tunnelled request")
    check(not auth.ingress_is_admin(forged),
          "a stranger could claim to be the HA admin from the internet")

    check(not auth.ingress_is_admin({'x-ingress-path': '/x', 'x-hass-is-admin': 'false'}),
          "a non-admin HA user was treated as an admin")


def scenario_k_the_first_run_grace_closes_by_itself():
    """No dated switch anybody has to remember: the moment a parent holds a
    password, the household has an owner and the bootstrap is shut."""
    import main
    # Earlier scenarios in this file set passwords on parents, so start from a
    # household that genuinely has no owner rather than assuming one.
    for existing in storage.get_all_members():
        if existing.get('password_hash'):
            storage.clear_member_password(existing['id'])
    m = _member('Owner', role='parent')
    check(not main._any_parent_has_password(),
          "a parent with no password counted as a claimed household")
    storage.set_member_password(m, 'correct horse battery')
    check(main._any_parent_has_password(),
          "the household did not read as claimed once a parent had a password")


def scenario_l_rate_limiting_survives_a_restart_and_backs_off():
    """It used to be a module dict, and this project rebuilds the add-on on
    every release — so patience beat the lockout."""
    key = 'test:rate'
    storage.rate_clear(key)
    for _ in range(4):
        storage.rate_record(key, False)
    check(not storage.rate_locked(key), "locked out before the threshold")
    storage.rate_record(key, False)          # the fifth
    check(storage.rate_locked(key), "the threshold did not lock anything")

    # It is in the database, not in a process — which is the whole fix.
    with storage.db_lock:
        rows = storage.rate_limits_table.search(storage.Query().key == key)
    check(rows and rows[0]['locked_until'] > 0,
          "the lockout was not persisted, so a rebuild would clear it")

    # And the backoff grows rather than staying at a flat 30 seconds.
    first = rows[0]['locked_until']
    storage.rate_clear(key)
    for _ in range(10):
        storage.rate_record(key, False)      # two trips
    with storage.db_lock:
        rows = storage.rate_limits_table.search(storage.Query().key == key)
    check(rows[0]['trips'] == 2, f"the trip counter did not grow: {rows[0]}")
    storage.rate_clear(key)


def scenario_l2_one_kids_typos_cannot_lock_out_the_household():
    """The PWA is installed against the public hostname, so every phone in the
    house arrives with the SAME CF-Connecting-IP even from the kitchen. At the
    per-member threshold, one kid fumbling a PIN would have locked out both
    parents and the wall panel — a self-inflicted outage presenting as a
    mystery. The IP counter is a coarse net for enumeration, not for typos."""
    member_key, ip_key = 'member:kid', 'ip:203.0.113.7'
    storage.rate_clear(member_key)
    storage.rate_clear(ip_key)
    for _ in range(5):                       # one kid, five wrong PINs
        storage.rate_record(member_key, False)
        storage.rate_record(ip_key, False)
    check(storage.rate_locked(member_key),
          "the member who was guessing wrong was not slowed down at all")
    check(not storage.rate_locked(ip_key),
          "ONE member's typos locked out every device on the home address")
    # But a script walking the family still trips it.
    for _ in range(45):
        storage.rate_record(ip_key, False)
    check(storage.rate_locked(ip_key),
          "sustained guessing from one address was never throttled")
    storage.rate_clear(member_key)
    storage.rate_clear(ip_key)


def scenario_m_success_clears_the_lockout():
    """A family member who finally remembers their PIN is not punished for the
    four tries it took."""
    key = 'test:rate2'
    storage.rate_clear(key)
    for _ in range(3):
        storage.rate_record(key, False)
    storage.rate_record(key, True)
    with storage.db_lock:
        rows = storage.rate_limits_table.search(storage.Query().key == key)
    check(not rows, "a successful attempt did not clear the failure count")


def scenario_n_the_ip_counter_ignores_headers_the_caller_controls():
    """A rate limit keyed on something the attacker can rotate is decoration:
    X-Forwarded-For is client-supplied, CF-Connecting-IP is not."""
    from services import auth
    check(auth.caller_ip({'cf-connecting-ip': '203.0.113.7'}) == '203.0.113.7',
          "the trustworthy address header was ignored")
    check(auth.caller_ip({'x-forwarded-for': '203.0.113.7'}) is None,
          "a client-supplied address header was used for rate limiting")


SCENARIOS = [v for k, v in sorted(globals().items()) if k.startswith("scenario_")]



# --- S5: the PIN is demoted, not deleted ------------------------------------

def scenario_o_a_pin_opens_a_trusted_device_and_nothing_else():
    """Four digits is a fine 'let me back in on the kitchen tablet' and a
    hopeless 'anybody on the internet who knows the family's names'."""
    storage.untrust_device('tablet-1')
    check(storage.get_trusted_device('tablet-1') is None,
          "an unknown device started out trusted")
    storage.trust_device('tablet-1', label='Kitchen tablet', by_member='mum')
    d = storage.get_trusted_device('tablet-1')
    check(d and d['label'] == 'Kitchen tablet',
          f"signing in did not vouch for the device: {d}")
    # Trusting twice is a re-visit, not a duplicate row.
    storage.trust_device('tablet-1', by_member='mum')
    check(len([x for x in storage.get_trusted_devices()
               if x['device_id'] == 'tablet-1']) == 1,
          "the same device was trusted twice over")
    storage.untrust_device('tablet-1')
    check(storage.get_trusted_device('tablet-1') is None,
          "revoking a device did not actually revoke it")


def scenario_p_young_children_are_never_asked_for_an_email():
    """A five-year-old has no inbox, and requiring one to appear on the
    family's schedule would be absurd. The stage says so, so no surface has to
    know a birthday."""
    from services import stages
    for stage in ('sprout', 'explorer'):
        check(stages.CAPABILITIES[stage]['own_account'] is False,
              f"{stage} was offered an account of their own")
    for stage in ('navigator', 'copilot'):
        check(stages.CAPABILITIES[stage]['own_account'] is True,
              f"{stage} could not hold an account")
    # And it is OFFERED, never forced: a Navigator with no email keeps the PIN
    # and loses nothing, which is why nothing here refuses a member.
    check('own_account' in stages.CAPABILITIES['navigator'],
          "the capability is how a surface asks; it must exist by name")


def scenario_q_growing_up_says_what_is_new():
    """Growing up is GRANTED (A4), so a new capability has to be something the
    family is told about rather than something that silently appears."""
    from services import stages
    grants = ' '.join(stages.GRANTS['navigator']).lower()
    check('account' in grants,
          f"moving up to Navigator gained an account without saying so: {grants}")


SCENARIOS = [v for k, v in sorted(globals().items()) if k.startswith("scenario_")]



# --- S6: a panel is a place, not a person -----------------------------------

def scenario_r_a_device_token_must_be_issued_not_merely_sent():
    """S1 returned the device tier to anybody who sent the header at all,
    which would have made the header its own password — the exact shape of
    hole this arc exists to close. It was dark, so never reachable, but it had
    to be right BEFORE the flip rather than at it."""
    from services import auth
    who = auth.identify({'x-device-token': 'i-just-made-this-up'}, {})
    check(who['tier'] != auth.DEVICE,
          "an invented device token was accepted as an enrolled panel")

    storage.untrust_device('panel-1')
    token = storage.enrol_device_token('panel-1', 'Kitchen panel', by_member='mum')
    who = auth.identify({'x-device-token': token, 'cf-connecting-ip': '203.0.113.7'}, {})
    check(who['tier'] == auth.DEVICE,
          f"a real panel token was not honoured: {who}")
    check(who.get('device', {}).get('label') == 'Kitchen panel',
          "the panel's identity did not come back with it")


def scenario_s_a_panel_gets_the_room_not_the_admin_keys():
    """It gets the powers of the room it is bolted to, never the powers of
    whoever last walked past it."""
    from services import auth
    board = auth.resolve('GET', '/api/home_board/build')
    check(auth.DEVICE in board, "a panel could not draw its own board")
    for admin in ('/api/settings', '/api/download_db', '/config'):
        tiers = auth.resolve('GET', admin) or frozenset()
        check(auth.DEVICE not in tiers,
              f"a wall panel could reach {admin}")


def scenario_t_the_device_asks_and_a_parent_answers():
    """The direction is the design. An earlier draft had a parent mint the
    code and somebody type it into the panel, which sent the secret TO the
    untrusted screen and made a person stand at a hallway touchscreen typing
    six digits. The device asks; the human approves where they are already
    signed in; the panel never takes input."""
    storage.clear_pairing('panel-9')
    storage.untrust_device('panel-9')
    storage.request_pairing('panel-9', '123456', ttl_minutes=15,
                            context={'from': 'this network'})

    # The screen is waiting, and nothing has been granted yet.
    waiting = storage.get_pairing_by_code('123456')
    check(waiting and waiting['device_id'] == 'panel-9',
          "the screen's request was not findable by its code")
    check(not waiting.get('device_token'),
          "asking to pair handed out a token before anybody approved")
    check(storage.get_pairing_by_device('panel-9')['approved_at'] is None,
          "the request started out approved")

    # A parent says yes.
    done = storage.approve_pairing('123456', 'Kitchen panel', by_member='mum')
    check(done and done['device_token'], f"approval minted no token: {done}")
    check(storage.get_device_by_token(done['device_token']) is not None,
          "the approved token was not usable")

    # And the code cannot be spent twice.
    check(storage.get_pairing_by_code('123456') is None,
          "an approved code was still live for a second screen")
    storage.clear_pairing('panel-9')


def scenario_t2_asking_again_replaces_the_old_code():
    """A screen left up all night re-asks; two live codes for one panel would
    mean a parent could approve one nobody is looking at."""
    storage.clear_pairing('panel-10')
    storage.request_pairing('panel-10', '111111', ttl_minutes=15)
    storage.request_pairing('panel-10', '222222', ttl_minutes=15)
    check(storage.get_pairing_by_code('111111') is None,
          "the old code stayed live after the screen asked again")
    check(storage.get_pairing_by_code('222222') is not None,
          "the new code did not take")
    storage.clear_pairing('panel-10')


def scenario_t3_an_expired_request_is_never_approvable():
    storage.clear_pairing('panel-11')
    storage.request_pairing('panel-11', '333333', ttl_minutes=0)
    check(storage.get_pairing_by_code('333333') is None,
          "an expired pairing request was still offered")
    check(storage.approve_pairing('333333', 'Nope') is None,
          "an expired pairing request could still be approved")
    storage.clear_pairing('panel-11')


def scenario_u_a_service_token_must_match_the_configured_one():
    """Same lesson as the device token: presence is not proof."""
    from services import auth
    real_settings = storage.get_settings
    storage.get_settings = lambda: {'service_token': 'the-real-one'}
    try:
        check(auth.identify({'x-service-token': 'guessed',
                             'cf-connecting-ip': '203.0.113.7'}, {})['tier'] != auth.SERVICE,
              "a guessed service token was accepted")
        check(auth.identify({'x-service-token': 'the-real-one',
                             'cf-connecting-ip': '203.0.113.7'}, {})['tier'] == auth.SERVICE,
              "the configured service token was rejected")
    finally:
        storage.get_settings = real_settings


SCENARIOS = [v for k, v in sorted(globals().items()) if k.startswith("scenario_")]

if __name__ == "__main__":
    for fn in SCENARIOS:
        fn()
        print(f"  ok  {fn.__name__}")
    print(f"\n{len(SCENARIOS)}/{len(SCENARIOS)} account scenarios passed")
