"""Accounts: invite, verify, password, reset (auth arc S3).

Adding a person IS creating a user. The properties pinned here are the ones
that would be quietly wrong for months otherwise:

  1. **A link is single-use and expires.** A reset link that stays live in a
     mailbox is a spare key under the mat.
  2. **Setting a password kills every other outstanding link.** Otherwise an
     old invite still sitting in a forwarded email survives the password
     change it was supposed to be replaced by.
  3. **Nothing leaks whether an address exists.** Both the login failure and
     the forgot-password response are identical either way, because whether a
     given address is on this family's account is not a stranger's to test.
  4. **Hashes never reach a surface.** `_public_member` is the one chokepoint,
     and a hash that leaks once is offline-crackable forever.
  5. **Mail is never a hard dependency** — no sender configured still produces
     a working link.

Run from chauffeur/:  python tests/test_accounts.py
"""
import time

from harness import check  # noqa: F401  (isolates CHAUFFEUR_DATA_DIR)

from services import storage, mailer


def _member(name='Vovo', role='parent', email=None):
    """`add_member` returns the TinyDB doc id, not the member id — the app's
    ids are generated by the schema, so the test supplies one."""
    import uuid
    mid = uuid.uuid4().hex
    storage.add_member({'id': mid, 'name': name, 'role': role, 'email': email})
    return mid


def scenario_a_a_link_is_single_use():
    m = _member('Single')
    token = storage.create_auth_link(m, 'invite')
    check(storage.peek_auth_link(token) is not None,
          "a fresh link did not read as valid")
    check(storage.consume_auth_link(token) is not None,
          "a fresh link could not be spent")
    check(storage.consume_auth_link(token) is None,
          "a spent link was accepted a second time — that is a spare key")
    check(storage.peek_auth_link(token) is None,
          "a spent link still peeks as valid")


def scenario_b_a_link_expires():
    m = _member('Expiry')
    token = storage.create_auth_link(m, 'reset', ttl_hours=0)
    # ttl 0 means already expired; no sleeping in tests.
    check(storage.peek_auth_link(token) is None,
          "an expired link was still accepted")


def scenario_c_setting_a_password_kills_the_other_links():
    """The forwarded-invite problem: an old link must not outlive the password
    it was meant to create."""
    m = _member('Twice')
    first = storage.create_auth_link(m, 'invite')
    second = storage.create_auth_link(m, 'invite')
    storage.consume_auth_link(second)
    storage.set_member_password(m, 'correct horse battery')
    storage.invalidate_auth_links(m)
    check(storage.peek_auth_link(first) is None,
          "an earlier invite survived the password being set")


def scenario_d_passwords_verify_and_do_not_leak():
    m = _member('Hashy')
    storage.set_member_password(m, 'correct horse battery')
    check(storage.verify_member_password(m, 'correct horse battery'),
          "the right password was rejected")
    check(not storage.verify_member_password(m, 'wrong horse battery'),
          "the wrong password was accepted")
    check(not storage.verify_member_password(m, ''),
          "an empty password was accepted")
    # The chokepoint. If this ever regresses, a hash is on a kiosk.
    import main
    pub = main._public_member(storage.get_member(m))
    for field in ('password_hash', 'password_salt', 'pin_hash', 'pin_salt'):
        check(field not in pub, f"{field} leaked through _public_member")
    check(pub.get('has_password') is True,
          "has_password is how a surface asks; it was not set")


def scenario_e_a_member_with_no_password_is_not_almost_signed_in():
    """Absence of a credential must never read as a match — the classic
    empty-hash-equals-empty-input bug."""
    m = _member('Nopass')
    check(not storage.verify_member_password(m, ''),
          "a member with no password verified against an empty string")
    check(not storage.verify_member_password(m, 'anything'),
          "a member with no password verified against a guess")


def scenario_f_email_lookup_is_case_insensitive():
    _member('Casey', email='Casey.Jones@Example.COM')
    check(storage.get_member_by_email('casey.jones@example.com') is not None,
          "an address typed in a different case did not find the account")
    check(storage.get_member_by_email('  CASEY.JONES@EXAMPLE.COM  ') is not None,
          "surrounding whitespace defeated the lookup")
    check(storage.get_member_by_email('nobody@example.com') is None,
          "an unknown address matched somebody")


def scenario_g_mail_is_never_a_hard_dependency():
    """No sender configured is a normal state, not an error: the invite still
    produces a link a parent can hand over."""
    check(not mailer.configured({}),
          "an empty settings dict read as a configured mail sender")
    out = mailer.send('someone@example.com', 'Subject', 'Body', settings={})
    check(out['sent'] is False and out['reason'],
          f"an unconfigured send did not report why: {out}")
    # And it never raises — the caller's fallback is better than a 500.
    out = mailer.send('not-an-address', 'Subject', 'Body', settings={})
    check(out['sent'] is False, "an invalid address did not fail softly")


def scenario_h_the_reuse_toggle_mirrors_intake_rather_than_copying():
    """`smtp_use_intake` must READ intake's values, not have copied them at
    save time — a copy fossilises a password the family later changes in one
    place and not the other."""
    settings = {'smtp_use_intake': True, 'ingest_email_host': 'imap.gmail.com',
                'ingest_email_user': 'family@gmail.com',
                'ingest_email_password': 'app-pw'}
    cfg = mailer.config(settings)
    check(cfg['user'] == 'family@gmail.com' and cfg['password'] == 'app-pw',
          f"the toggle did not mirror the intake credentials: {cfg}")
    check(cfg['host'] == 'smtp.gmail.com',
          f"the IMAP host was not translated for sending: {cfg['host']}")
    check(cfg['from'] == 'family@gmail.com',
          "reuse should send as the intake address itself")
    # Changing intake's password changes the sender's, with no second save.
    settings['ingest_email_password'] = 'new-pw'
    check(mailer.config(settings)['password'] == 'new-pw',
          "the mirror had gone stale — it copied instead of reading")


def scenario_i_a_from_address_the_account_does_not_own_is_flagged():
    """Said in the form, because the failure is otherwise a silent bounce."""
    warn = mailer.from_address_warning(
        {'smtp_user': 'family@gmail.com', 'smtp_from': 'noreply@example.com'})
    check(warn and 'reject' in warn,
          f"a mismatched From address was not flagged: {warn}")
    check(mailer.from_address_warning(
        {'smtp_user': 'family@gmail.com', 'smtp_from': 'family@gmail.com'}) is None,
        "a matching From address was flagged anyway")


SCENARIOS = [v for k, v in sorted(globals().items()) if k.startswith("scenario_")]

if __name__ == "__main__":
    for fn in SCENARIOS:
        fn()
        print(f"  ok  {fn.__name__}")
    print(f"\n{len(SCENARIOS)}/{len(SCENARIOS)} account scenarios passed")
