"""Accounts: invite, verify, password, reset (auth arc S3).

Adding a person IS creating a user. The properties pinned here are the ones
that would be quietly wrong for months otherwise:

  1. **A link is single-use and expires.** A reset link that stays live in a
     mailbox is a spare key under the mat.
  2. **Setting a password kills every other outstanding link.** Otherwise an
     old invite still sitting in a forwarded email survives the password
     change it was supposed to be replaced by.
  3. **Nothing leaks whether an address exists.** Both the login failure and
     the forgot-password response are identical either way, because whether a
     given address is on this family's account is not a stranger's to test.
  4. **Hashes never reach a surface.** `_public_member` is the one chokepoint,
     and a hash that leaks once is offline-crackable forever.
  5. **Mail is never a hard dependency** — no sender configured still produces
     a working link.

Run from chauffeur/:  python tests/test_accounts.py
"""
import time

from harness import check  # noqa: F401  (isolates CHAUFFEUR_DATA_DIR)

from services import storage, mailer


def _member(name='Vovo', role='parent', email=None):
    """`add_member` returns the TinyDB doc id, not the member id — the app's
    ids are generated by the schema, so the test supplies one."""
    import uuid
    mid = uuid.uuid4().hex
    storage.add_member({'id': mid, 'name': name, 'role': role, 'email': email})
    return mid


def scenario_a_a_link_is_single_use():
    m = _member('Single')
    token = storage.create_auth_link(m, 'invite')
    check(storage.peek_auth_link(token) is not None,
          "a fresh link did not read as valid")
    check(storage.consume_auth_link(token) is not None,
          "a fresh link could not be spent")
    check(storage.consume_auth_link(token) is None,
          "a spent link was accepted a second time — that is a spare key")
    check(storage.peek_auth_link(token) is None,
          "a spent link still peeks as valid")


def scenario_b_a_link_expires():
    m = _member('Expiry')
    token = storage.create_auth_link(m, 'reset', ttl_hours=0)
    # ttl 0 means already expired; no sleeping in tests.
    check(storage.peek_auth_link(token) is None,
          "an expired link was still accepted")


def scenario_c_setting_a_password_kills_the_other_links():
    """The forwarded-invite problem: an old link must not outlive the password
    it was meant to create."""
    m = _member('Twice')
    first = storage.create_auth_link(m, 'invite')
    second = storage.create_auth_link(m, 'invite')
    storage.consume_auth_link(second)
    storage.set_member_password(m, 'correct horse battery')
    storage.invalidate_auth_links(m)
    check(storage.peek_auth_link(first) is None,
          "an earlier invite survived the password being set")


def scenario_d_passwords_verify_and_do_not_leak():
    m = _member('Hashy')
    storage.set_member_password(m, 'correct horse battery')
    check(storage.verify_member_password(m, 'correct horse battery'),
          "the right password was rejected")
    check(not storage.verify_member_password(m, 'wrong horse battery'),
          "the wrong password was accepted")
    check(not storage.verify_member_password(m, ''),
          "an empty password was accepted")
    # The chokepoint. If this ever regresses, a hash is on a kiosk.
    import main
    pub = main._public_member(storage.get_member(m))
    for field in ('password_hash', 'password_salt', 'pin_hash', 'pin_salt'):
        check(field not in pub, f"{field} leaked through _public_member")
    check(pub.get('has_password') is True,
          "has_password is how a surface asks; it was not set")


def scenario_e_a_member_with_no_password_is_not_almost_signed_in():
    """Absence of a credential must never read as a match — the classic
    empty-hash-equals-empty-input bug."""
    m = _member('Nopass')
    check(not storage.verify_member_password(m, ''),
          "a member with no password verified against an empty string")
    check(not storage.verify_member_password(m, 'anything'),
          "a member with no password verified against a guess")


def scenario_f_email_lookup_is_case_insensitive():
    _member('Casey', email='Casey.Jones@Example.COM')
    check(storage.get_member_by_email('casey.jones@example.com') is not None,
          "an address typed in a different case did not find the account")
    check(storage.get_member_by_email('  CASEY.JONES@EXAMPLE.COM  ') is not None,
          "surrounding whitespace defeated the lookup")
    check(storage.get_member_by_email('nobody@example.com') is None,
          "an unknown address matched somebody")


def scenario_g_mail_is_never_a_hard_dependency():
    """No sender configured is a normal state, not an error: the invite still
    produces a link a parent can hand over."""
    check(not mailer.configured({}),
          "an empty settings dict read as a configured mail sender")
    out = mailer.send('someone@example.com', 'Subject', 'Body', settings={})
    check(out['sent'] is False and out['reason'],
          f"an unconfigured send did not report why: {out}")
    # And it never raises — the caller's fallback is better than a 500.
    out = mailer.send('not-an-address', 'Subject', 'Body', settings={})
    check(out['sent'] is False, "an invalid address did not fail softly")


def scenario_h_the_reuse_toggle_mirrors_intake_rather_than_copying():
    """`smtp_use_intake` must READ intake's values, not have copied them at
    save time — a copy fossilises a password the family later changes in one
    place and not the other."""
    settings = {'smtp_use_intake': True, 'ingest_email_host': 'imap.gmail.com',
                'ingest_email_user': 'family@gmail.com',
                'ingest_email_password': 'app-pw'}
    cfg = mailer.config(settings)
    check(cfg['user'] == 'family@gmail.com' and cfg['password'] == 'app-pw',
          f"the toggle did not mirror the intake credentials: {cfg}")
    check(cfg['host'] == 'smtp.gmail.com',
          f"the IMAP host was not translated for sending: {cfg['host']}")
    check(cfg['from'] == 'family@gmail.com',
          "reuse should send as the intake address itself")
    # Changing intake's password changes the sender's, with no second save.
    settings['ingest_email_password'] = 'new-pw'
    check(mailer.config(settings)['password'] == 'new-pw',
          "the mirror had gone stale — it copied instead of reading")


def scenario_i_a_from_address_the_account_does_not_own_is_flagged():
    """Said in the form, because the failure is otherwise a silent bounce."""
    warn = mailer.from_address_warning(
        {'smtp_user': 'family@gmail.com', 'smtp_from': 'noreply@example.com'})
    check(warn and 'reject' in warn,
          f"a mismatched From address was not flagged: {warn}")
    check(mailer.from_address_warning(
        {'smtp_user': 'family@gmail.com', 'smtp_from': 'family@gmail.com'}) is None,
        "a matching From address was flagged anyway")


# --- S4: the admin surface gets an identity ---------------------------------

def scenario_j_ingress_headers_are_only_believed_off_the_tunnel():
    """The trap this avoids is worse than the hole being closed: `X-Hass-Is-
    Admin` is trivially forged, so believing it on a tunnelled request would
    hand the household to anyone who read the source.

    The discriminator is CLOUDFLARE's own headers, not `X-Forwarded-For`.
    That distinction is the bug this scenario grew: supervisor sets
    `X-Forwarded-For` itself when proxying ingress, so leaning on it made
    every genuine ingress request look external and the first-run panel could
    never appear."""
    from services import auth
    ingress = {'x-ingress-path': '/api/hassio_ingress/abc', 'x-hass-is-admin': 'true'}
    check(auth.arrived_via_ingress(ingress),
          "a genuine ingress request was not recognised")
    check(auth.ingress_is_admin(ingress), "an HA admin was not recognised")

    # Supervisor proxies with X-Forwarded-For. This MUST still read as ingress.
    proxied = {'x-ingress-path': '/api/hassio_ingress/abc',
               'x-forwarded-for': '192.168.1.50', 'x-forwarded-proto': 'https'}
    check(auth.arrived_via_ingress(proxied),
          "supervisor's own X-Forwarded-For disqualified a real ingress request")
    check(auth.ingress_is_admin(proxied),
          "first-run was impossible on an install whose supervisor sends no admin flag")

    # Header spellings differ by supervisor version; all the plausible ones count.
    for spelling in ('x-remote-user-id', 'x-remote-user-name', 'x-hass-user-id'):
        check(auth.arrived_via_ingress({spelling: 'abc'}),
              f"ingress went unrecognised when identified by {spelling}")

    forged = dict(ingress)
    forged['cf-connecting-ip'] = '203.0.113.7'      # came through cloudflared
    check(not auth.arrived_via_ingress(forged),
          "FORGED ingress headers were believed on a tunnelled request")
    check(not auth.ingress_is_admin(forged),
          "a stranger could claim to be the HA admin from the internet")
    check(not auth.arrived_via_ingress({**ingress, 'cf-ray': 'abc123'}),
          "CF-Ray alone did not mark a request as coming through the tunnel")

    check(not auth.ingress_is_admin({'x-ingress-path': '/x', 'x-hass-is-admin': 'false'}),
          "a non-admin HA user was treated as an admin")


def scenario_k_the_first_run_grace_closes_by_itself():
    """No dated switch anybody has to remember: the moment a parent holds a
    password, the household has an owner and the bootstrap is shut."""
    import main
    # Earlier scenarios in this file set passwords on parents, so start from a
    # household that genuinely has no owner rather than assuming one.
    for existing in storage.get_all_members():
        if existing.get('password_hash'):
            storage.clear_member_password(existing['id'])
    m = _member('Owner', role='parent')
    check(not main._any_parent_has_password(),
          "a parent with no password counted as a claimed household")
    storage.set_member_password(m, 'correct horse battery')
    check(main._any_parent_has_password(),
          "the household did not read as claimed once a parent had a password")


def scenario_l_rate_limiting_survives_a_restart_and_backs_off():
    """It used to be a module dict, and this project rebuilds the add-on on
    every release — so patience beat the lockout."""
    key = 'test:rate'
    storage.rate_clear(key)
    for _ in range(4):
        storage.rate_record(key, False)
    check(not storage.rate_locked(key), "locked out before the threshold")
    storage.rate_record(key, False)          # the fifth
    check(storage.rate_locked(key), "the threshold did not lock anything")

    # It is in the database, not in a process — which is the whole fix.
    with storage.db_lock:
        rows = storage.rate_limits_table.search(storage.Query().key == key)
    check(rows and rows[0]['locked_until'] > 0,
          "the lockout was not persisted, so a rebuild would clear it")

    # And the backoff grows rather than staying at a flat 30 seconds.
    first = rows[0]['locked_until']
    storage.rate_clear(key)
    for _ in range(10):
        storage.rate_record(key, False)      # two trips
    with storage.db_lock:
        rows = storage.rate_limits_table.search(storage.Query().key == key)
    check(rows[0]['trips'] == 2, f"the trip counter did not grow: {rows[0]}")
    storage.rate_clear(key)


def scenario_l2_one_kids_typos_cannot_lock_out_the_household():
    """The PWA is installed against the public hostname, so every phone in the
    house arrives with the SAME CF-Connecting-IP even from the kitchen. At the
    per-member threshold, one kid fumbling a PIN would have locked out both
    parents and the wall panel — a self-inflicted outage presenting as a
    mystery. The IP counter is a coarse net for enumeration, not for typos."""
    member_key, ip_key = 'member:kid', 'ip:203.0.113.7'
    storage.rate_clear(member_key)
    storage.rate_clear(ip_key)
    for _ in range(5):                       # one kid, five wrong PINs
        storage.rate_record(member_key, False)
        storage.rate_record(ip_key, False)
    check(storage.rate_locked(member_key),
          "the member who was guessing wrong was not slowed down at all")
    check(not storage.rate_locked(ip_key),
          "ONE member's typos locked out every device on the home address")
    # But a script walking the family still trips it.
    for _ in range(45):
        storage.rate_record(ip_key, False)
    check(storage.rate_locked(ip_key),
          "sustained guessing from one address was never throttled")
    storage.rate_clear(member_key)
    storage.rate_clear(ip_key)


def scenario_m_success_clears_the_lockout():
    """A family member who finally remembers their PIN is not punished for the
    four tries it took."""
    key = 'test:rate2'
    storage.rate_clear(key)
    for _ in range(3):
        storage.rate_record(key, False)
    storage.rate_record(key, True)
    with storage.db_lock:
        rows = storage.rate_limits_table.search(storage.Query().key == key)
    check(not rows, "a successful attempt did not clear the failure count")


def scenario_n_the_ip_counter_ignores_headers_the_caller_controls():
    """A rate limit keyed on something the attacker can rotate is decoration:
    X-Forwarded-For is client-supplied, CF-Connecting-IP is not."""
    from services import auth
    check(auth.caller_ip({'cf-connecting-ip': '203.0.113.7'}) == '203.0.113.7',
          "the trustworthy address header was ignored")
    check(auth.caller_ip({'x-forwarded-for': '203.0.113.7'}) is None,
          "a client-supplied address header was used for rate limiting")


SCENARIOS = [v for k, v in sorted(globals().items()) if k.startswith("scenario_")]



# --- S5: the PIN is demoted, not deleted ------------------------------------

def scenario_o_a_pin_opens_a_trusted_device_and_nothing_else():
    """Four digits is a fine 'let me back in on the kitchen tablet' and a
    hopeless 'anybody on the internet who knows the family's names'."""
    storage.untrust_device('tablet-1')
    check(storage.get_trusted_device('tablet-1') is None,
          "an unknown device started out trusted")
    storage.trust_device('tablet-1', label='Kitchen tablet', by_member='mum')
    d = storage.get_trusted_device('tablet-1')
    check(d and d['label'] == 'Kitchen tablet',
          f"signing in did not vouch for the device: {d}")
    # Trusting twice is a re-visit, not a duplicate row.
    storage.trust_device('tablet-1', by_member='mum')
    check(len([x for x in storage.get_trusted_devices()
               if x['device_id'] == 'tablet-1']) == 1,
          "the same device was trusted twice over")
    storage.untrust_device('tablet-1')
    check(storage.get_trusted_device('tablet-1') is None,
          "revoking a device did not actually revoke it")


def scenario_the_set_password_page_is_the_first_thing_the_app_ever_shows():
    """A standalone page with no shell, opened from a mail client by somebody
    who may never have heard of Chauffeur. It should look like the app they are
    about to be handed, and it must not lie about the rule it enforces.

    The minimum is pinned across the Python/template boundary: the button
    disables below it, and a form that lets somebody type nine characters and
    press Set password only to be refused by the server has wasted the one
    interaction it gets.
    """
    import main
    import tpl_source
    page = tpl_source.read('set_password.html')

    # The app's own mark, not a second one invented for this screen.
    nav = tpl_source.read('nav.html')
    mark = 'M13 10V3L4 14h7v7l9-11h-7z'
    check(mark in nav and mark in page,
          "the set-password page does not carry the app's wordmark")
    check('from-blue-400 to-indigo-400' in page,
          "the wordmark is drawn in colours the rest of the app does not use")

    # Themed by the token layer rather than by hand, or this one page keeps a
    # palette of its own that drifts from every other surface.
    check("'static/theme.css'|ver" in page,
          "the page does not load the theme tokens, so it cannot follow the "
          "app's light and dark")
    check('prefers-color-scheme' in page,
          "nobody opening an invite has a stored theme choice, so the OS "
          "preference is the only signal there is")

    check(f'password.length < {main._MIN_PASSWORD}' in page,
          f"the form's minimum drifted from the server's "
          f"({main._MIN_PASSWORD}) — somebody types a short password, presses "
          f"the button and is refused by an endpoint instead of the field")
    check(f'At least {main._MIN_PASSWORD} characters' in page,
          "the page states a different minimum than it enforces")

    # Accepting an invite IS a password sign-in, and password sign-ins vouch
    # the device they happen on (S5). This page has no nav wrapper, so it has
    # to carry the header itself — without it, `_trust_this_device` silently
    # no-ops and the phone the invite was accepted on never becomes trusted:
    # the day the token dies, the member's PIN cannot reopen it and the
    # rescue is a second invite.
    check("'X-Device-Id'" in page and 'chauffeur_device_id' in page,
          "the set-password page never names its device, so accepting an "
          "invite signs somebody in without vouching the phone it happened on")


def scenario_an_invite_finishes_the_account_it_started():
    """An invite hands over an account. It should hand over a WORKING one, and
    twice it did not — both times because the next surface assumed somebody had
    arrived by a route they had not taken.

      * **No PIN was ever offered.** The app offers one inside
        `ensureMemberAuth`, which returns early when a token for that member is
        already stored — precisely what this page writes. So an invited member
        was never asked, and would meet S8's token expiry three months later
        typing a password on a kitchen tablet: the friction S5 demoted the PIN
        to prevent. Offered here instead, and skipping burns the same marker
        `offerPinSetup` uses, so declining once is an answer.
      * **A driver was sent to the picker.** The page wrote `member_id` but
        never `driver_id`, and the app only auto-restores a NON-driver — so
        anyone with a driver identity was asked who they were seconds after
        proving it.
    """
    import main
    import tpl_source
    page = tpl_source.read('set_password.html')

    check("state === 'pin'" in page and 'savePin()' in page and 'skipPin()' in page,
          "the invite never offers a PIN, and the app cannot: its own offer "
          "sits behind an early return this page's token satisfies")
    check("has_pin ? 'done' : 'pin'" in page,
          "a member a parent already gave a PIN is asked for another one")
    check('chauffeur_pin_offered_' in page,
          "skipping here does not burn the app's own offer marker, so the "
          "question is asked again on the next screen")
    # The format the server enforces, pinned across the boundary like the
    # password minimum above it.
    check(all(main._valid_pin_format(p) for p in ('1234', '12345678'))
          and not main._valid_pin_format('123'),
          "the server's PIN rule is not 4-8 digits any more")
    check('4,8' in page,
          "the form accepts a PIN length the server will reject")

    check('chauffeur_driver_id' in page,
          "an invited member who is a driver still lands on Select Family "
          "Member, having just proved exactly who they are")


def scenario_an_invite_link_carries_an_address_that_works():
    """`{"detail":"Not Found"}`, reported by the household from a link that had
    just been mailed. The route was fine; the ADDRESS in front of it was not.

    `_account_link` pasted `public_base_url` in front of the path and did
    nothing when that setting was empty — producing a bare
    `/account/set-password?token=…`, sent to somebody's phone, routable from
    nowhere. The push lane learned this already ("a mismatched or stale
    public_base_url must never be what 404s the tap") and went relative; an
    email cannot, so it falls back to the origin of the request that minted it.
    A parent issuing an invite is by definition holding a working address.

    And whatever is wrong with it is said in front of the PARENT, while they
    still have the link — the next person to find out is a grandparent looking
    at a 404 with nobody to ask.
    """
    import main
    from starlette.requests import Request

    def _req(headers):
        return Request({'type': 'http', 'method': 'POST', 'path': '/x',
                        'headers': [(k.encode(), v.encode())
                                    for k, v in headers.items()],
                        'query_string': b'', 'scheme': 'http',
                        'server': ('addon', 8000), 'root_path': ''})

    # `harness` stubs `storage.get_settings` to a constant, so the setting is
    # swapped on the accessor rather than written to the database.
    real_get = storage.get_settings

    def _with(url):
        storage.get_settings = lambda: {'calendar_ids': [], 'public_base_url': url}

    tunnel = _req({'host': 'chauffeur.example.com', 'x-forwarded-proto': 'https'})
    try:
        # No setting: the request's own origin, forwarded scheme honoured, or
        # every link minted behind the tunnel would say http:// and name the
        # container.
        _with('')
        link = main._account_link('TOK', tunnel)
        check(link == 'https://chauffeur.example.com/account/set-password?token=TOK',
              f"an invite mailed from the tunnel does not point at it: {link}")
        check(main._account_link_warning(link, tunnel) is None,
              "a link that is already right was complained about")

        # Nothing to go on at all: still flagged rather than mailed blind.
        bare = main._account_link('TOK')
        check(bare.startswith('/'), f"expected the bare path case: {bare}")
        check(main._account_link_warning(bare),
              "a link with no address in front of it was sent without a word")

        # Ingress: the token in that path rotates, so a link built from it is
        # dead by the time anybody clicks. Say so instead of minting it quietly.
        ing = _req({'host': 'ha.local:8123',
                    'x-ingress-path': '/api/hassio_ingress/AB12'})
        warn = main._account_link_warning(main._account_link('TOK', ing), ing)
        check(warn and 'ingress' in warn.lower(),
              f"an invite minted through ingress was not flagged: {warn}")

        # THE ONE THAT BIT THE HOUSEHOLD: the Public URL was the address they
        # actually use, `https://chauffeur.example.com/app` — and every consumer
        # appends its own absolute path, so the invite pointed at
        # `/app/account/set-password` and 404'd in an inbox. A trailing path
        # that names a page of ours is dropped; a mount prefix is not.
        _with('https://chauffeur.example.com/app')
        link = main._account_link('TOK', tunnel)
        check(link == 'https://chauffeur.example.com/account/set-password?token=TOK',
              f"a Public URL pointing at the PWA still poisons the invite: {link}")
        _with('https://host.example/chauffeur')
        link = main._account_link('TOK', tunnel)
        check(link.startswith('https://host.example/chauffeur/account/'),
              f"a genuine mount prefix was stripped: {link}")

        # A setting that no longer matches where the parent actually is.
        _with('http://192.168.1.9:8000')
        link = main._account_link('TOK', tunnel)
        check(link.startswith('http://192.168.1.9:8000'),
              f"an explicit Public URL lost to the request: {link}")
        warn = main._account_link_warning(link, tunnel)
        check(warn and '192.168.1.9:8000' in warn and 'chauffeur.example.com' in warn,
              f"a stale Public URL was mailed without comment: {warn}")
    finally:
        storage.get_settings = real_get


def scenario_o2_a_device_may_ask_what_it_is_called_but_only_about_itself():
    """Not parent-gated, unlike the list a lost tablet is revoked from: the
    caller already knows the id it is asking about — it minted the thing — so
    the answer carries nothing it did not bring.

    `named` is the half that matters. `trust_device` defaults the label to "A
    device" and pairing to "Wall panel", so a house with two paired panels has
    two devices with one label; a surface that treated that as an identity
    would register two Music Assistant players called the same thing, which is
    the bug this exists to stop.
    """
    import main

    class _Req:
        headers = {}
        query_params = {}

    storage.untrust_device('panel-named')
    storage.untrust_device('panel-default')
    storage.trust_device('panel-named', label='Kitchen tablet', by_member='mum')
    storage.trust_device('panel-default', by_member='mum')

    named = main.this_device(_Req(), 'panel-named')
    check(named['label'] == 'Kitchen tablet' and named['named'] is True,
          f"a device a parent named cannot find out what it is called: {named}")
    default = main.this_device(_Req(), 'panel-default')
    check(default['trusted'] is True and default['named'] is False,
          f"a default label was handed out as an identity: {default}")
    unknown = main.this_device(_Req(), 'never-seen')
    check(unknown['trusted'] is False and unknown['named'] is False,
          f"an unpaired device was answered for: {unknown}")
    none = main.this_device(_Req(), None)
    check(none['device_id'] is None and none['named'] is False,
          f"asking with no device id got an answer anyway: {none}")
    storage.untrust_device('panel-named')
    storage.untrust_device('panel-default')


def scenario_p_young_children_are_never_asked_for_an_email():
    """A five-year-old has no inbox, and requiring one to appear on the
    family's schedule would be absurd. The stage says so, so no surface has to
    know a birthday."""
    from services import stages
    for stage in ('sprout', 'explorer'):
        check(stages.CAPABILITIES[stage]['own_account'] is False,
              f"{stage} was offered an account of their own")
    for stage in ('navigator', 'copilot'):
        check(stages.CAPABILITIES[stage]['own_account'] is True,
              f"{stage} could not hold an account")
    # And it is OFFERED, never forced: a Navigator with no email keeps the PIN
    # and loses nothing, which is why nothing here refuses a member.
    check('own_account' in stages.CAPABILITIES['navigator'],
          "the capability is how a surface asks; it must exist by name")


def scenario_q_growing_up_says_what_is_new():
    """Growing up is GRANTED (A4), so a new capability has to be something the
    family is told about rather than something that silently appears."""
    from services import stages
    grants = ' '.join(stages.GRANTS['navigator']).lower()
    check('account' in grants,
          f"moving up to Navigator gained an account without saying so: {grants}")


SCENARIOS = [v for k, v in sorted(globals().items()) if k.startswith("scenario_")]



# --- S6: a panel is a place, not a person -----------------------------------

def scenario_r_a_device_token_must_be_issued_not_merely_sent():
    """S1 returned the device tier to anybody who sent the header at all,
    which would have made the header its own password — the exact shape of
    hole this arc exists to close. It was dark, so never reachable, but it had
    to be right BEFORE the flip rather than at it."""
    from services import auth
    who = auth.identify({'x-device-token': 'i-just-made-this-up'}, {})
    check(who['tier'] != auth.DEVICE,
          "an invented device token was accepted as an enrolled panel")

    storage.untrust_device('panel-1')
    token = storage.enrol_device_token('panel-1', 'Kitchen panel', by_member='mum')
    who = auth.identify({'x-device-token': token, 'cf-connecting-ip': '203.0.113.7'}, {})
    check(who['tier'] == auth.DEVICE,
          f"a real panel token was not honoured: {who}")
    check(who.get('device', {}).get('label') == 'Kitchen panel',
          "the panel's identity did not come back with it")


def scenario_s_a_panel_gets_the_room_not_the_admin_keys():
    """It gets the powers of the room it is bolted to, never the powers of
    whoever last walked past it."""
    from services import auth
    board = auth.resolve('GET', '/api/home_board/build')
    check(auth.DEVICE in board, "a panel could not draw its own board")
    for admin in ('/api/settings', '/api/download_db', '/config'):
        tiers = auth.resolve('GET', admin) or frozenset()
        check(auth.DEVICE not in tiers,
              f"a wall panel could reach {admin}")


def scenario_t_the_device_asks_and_a_parent_answers():
    """The direction is the design. An earlier draft had a parent mint the
    code and somebody type it into the panel, which sent the secret TO the
    untrusted screen and made a person stand at a hallway touchscreen typing
    six digits. The device asks; the human approves where they are already
    signed in; the panel never takes input."""
    storage.clear_pairing('panel-9')
    storage.untrust_device('panel-9')
    storage.request_pairing('panel-9', '123456', ttl_minutes=15,
                            context={'from': 'this network'})

    # The screen is waiting, and nothing has been granted yet.
    waiting = storage.get_pairing_by_code('123456')
    check(waiting and waiting['device_id'] == 'panel-9',
          "the screen's request was not findable by its code")
    check(not waiting.get('device_token'),
          "asking to pair handed out a token before anybody approved")
    check(storage.get_pairing_by_device('panel-9')['approved_at'] is None,
          "the request started out approved")

    # A parent says yes.
    done = storage.approve_pairing('123456', 'Kitchen panel', by_member='mum')
    check(done and done['device_token'], f"approval minted no token: {done}")
    check(storage.get_device_by_token(done['device_token']) is not None,
          "the approved token was not usable")

    # And the code cannot be spent twice.
    check(storage.get_pairing_by_code('123456') is None,
          "an approved code was still live for a second screen")
    storage.clear_pairing('panel-9')


def scenario_t2_asking_again_replaces_the_old_code():
    """A screen left up all night re-asks; two live codes for one panel would
    mean a parent could approve one nobody is looking at."""
    storage.clear_pairing('panel-10')
    storage.request_pairing('panel-10', '111111', ttl_minutes=15)
    storage.request_pairing('panel-10', '222222', ttl_minutes=15)
    check(storage.get_pairing_by_code('111111') is None,
          "the old code stayed live after the screen asked again")
    check(storage.get_pairing_by_code('222222') is not None,
          "the new code did not take")
    storage.clear_pairing('panel-10')


def scenario_t3_an_expired_request_is_never_approvable():
    storage.clear_pairing('panel-11')
    storage.request_pairing('panel-11', '333333', ttl_minutes=0)
    check(storage.get_pairing_by_code('333333') is None,
          "an expired pairing request was still offered")
    check(storage.approve_pairing('333333', 'Nope') is None,
          "an expired pairing request could still be approved")
    storage.clear_pairing('panel-11')


def scenario_u_a_service_token_must_match_the_configured_one():
    """Same lesson as the device token: presence is not proof."""
    from services import auth
    real_settings = storage.get_settings
    storage.get_settings = lambda: {'service_token': 'the-real-one'}
    try:
        check(auth.identify({'x-service-token': 'guessed',
                             'cf-connecting-ip': '203.0.113.7'}, {})['tier'] != auth.SERVICE,
              "a guessed service token was accepted")
        check(auth.identify({'x-service-token': 'the-real-one',
                             'cf-connecting-ip': '203.0.113.7'}, {})['tier'] == auth.SERVICE,
              "the configured service token was rejected")
    finally:
        storage.get_settings = real_settings


SCENARIOS = [v for k, v in sorted(globals().items()) if k.startswith("scenario_")]



# --- S7: Argyle gets a credential -------------------------------------------

def scenario_v_the_local_grace_is_a_switch_not_a_law():
    """The grace is what keeps Argyle alive through the migration, and turning
    it off has to be a deliberate act — a household that flips it before the
    integration has its token would just find Argyle gone quiet."""
    from services import auth
    real = storage.get_settings
    try:
        storage.get_settings = lambda: {'service_local_grace': True}
        who = auth.identify({}, {})
        check(who['tier'] == auth.SERVICE and who.get('via') == 'local-grace',
              f"the grace stopped applying while switched on: {who}")

        storage.get_settings = lambda: {'service_local_grace': False}
        who = auth.identify({}, {})
        check(who['tier'] is None,
              f"a local request was still trusted after the grace ended: {who}")

        # ...and with the grace off, the TOKEN is the way in.
        storage.get_settings = lambda: {'service_local_grace': False,
                                        'service_token': 'argyle-token'}
        who = auth.identify({'x-service-token': 'argyle-token'}, {})
        check(who['tier'] == auth.SERVICE,
              "Argyle could not get in with its own token")
    finally:
        storage.get_settings = real


def scenario_w_absent_grace_defaults_to_on():
    """Every install that predates S7 has no such key. Absent must mean ON, or
    deploying this release would silence Argyle in every household at once."""
    from services import auth
    real = storage.get_settings
    try:
        storage.get_settings = lambda: {}          # a pre-S7 settings row
        who = auth.identify({}, {})
        check(who['tier'] == auth.SERVICE,
              "upgrading silently cut Argyle off before anybody had a token")
    finally:
        storage.get_settings = real


def scenario_x_a_session_dies_of_old_age():
    """Decision 8: 90 days, enforced at the lookup so there is exactly one
    place a token can be believed. Expired means REMOVED, not merely refused —
    a dead row left behind would come back to life if the TTL were raised."""
    m = _member('Ninety')
    token = storage.create_member_token(m)
    check(storage.get_member_by_token(token) is not None,
          "a fresh session did not work")
    # Backdate the row past the TTL; no sleeping in tests.
    from tinydb import Query as _Q
    with storage.db_lock:
        storage.member_tokens_table.update(
            {'created_at': time.time() - storage.MEMBER_TOKEN_TTL_SECONDS - 1},
            _Q().token == token)
    check(storage.get_member_by_token(token) is None,
          "a 90-day-old session was still believed")
    with storage.db_lock:
        rows = storage.member_tokens_table.search(_Q().token == token)
    check(not rows, "an expired session was refused but left in the table")


def scenario_x2_a_token_with_no_birthday_is_grandfathered_not_executed():
    """Rows from before tokens carried created_at must NOT expire at deploy
    time — that would sign every phone in the household out at once. Absent
    means 'from now', written back so the clock actually starts."""
    m = _member('Elder')
    token = storage.create_member_token(m)
    from tinydb import Query as _Q
    with storage.db_lock:
        # TinyDB update() cannot remove a key; simulate a legacy row by
        # writing a falsy birthday, which the lookup treats as absent.
        storage.member_tokens_table.update({'created_at': None},
                                           _Q().token == token)
    check(storage.get_member_by_token(token) is not None,
          "a legacy token was killed by the upgrade instead of grandfathered")
    with storage.db_lock:
        row = storage.member_tokens_table.search(_Q().token == token)[0]
    check(row.get('created_at'),
          "the grandfathered token never got a birthday, so it can never age")


def scenario_x3_sign_out_everywhere_takes_the_vouched_phones_too():
    """Decision 8's stolen-phone lever, both halves. Sessions alone would be
    theatre: the stolen phone is trusted ground this member's own sign-in
    vouched, so their PIN would re-open it minutes later. The member's
    PERSONAL vouches die with the sessions; the wall panel (a place, and a
    parent's deliberate act) is untouched, and so is another member's phone."""
    thief_victim = _member('Vovo2')
    other = _member('Bystander')
    t1 = storage.create_member_token(thief_victim)
    t2 = storage.create_member_token(thief_victim)
    keep = storage.create_member_token(other)
    storage.trust_device('stolen-phone', 'Vovo2 phone',
                         by_member=thief_victim, kind='personal')
    storage.trust_device('kitchen-panel', 'Kitchen',
                         by_member=thief_victim, kind='panel')
    storage.trust_device('bystander-phone', 'Bystander phone',
                         by_member=other, kind='personal')
    sessions = storage.delete_member_tokens(thief_victim)
    devices = storage.untrust_devices_vouched_by(thief_victim)
    check(sessions == 2 and devices == 1,
          f"expected 2 sessions and 1 device gone, got {sessions} and {devices}")
    check(storage.get_member_by_token(t1) is None
          and storage.get_member_by_token(t2) is None,
          "a signed-out session still worked")
    check(storage.get_member_by_token(keep) is not None,
          "another member's session was collateral damage")
    check(storage.get_trusted_device('stolen-phone') is None,
          "the stolen phone stayed trusted ground — the PIN re-opens it")
    check(storage.get_trusted_device('kitchen-panel') is not None,
          "the wall panel lost its enrolment over one member's stolen phone")
    check(storage.get_trusted_device('bystander-phone') is not None,
          "another member's phone was un-trusted as collateral")


def scenario_y_the_flip_refuses_while_anyone_would_be_locked_out():
    """Decision 9: a switch that can lock a family out of their own house is
    not a bare checkbox. The settings POST refuses the false→true transition
    while any active member holds neither a password nor a PIN — and NAMES
    them, because "no" without a fix list is a dead end. Turning enforcement
    OFF is the emergency lever and must never be blocked by the same rule."""
    import main as _main
    from fastapi import BackgroundTasks, HTTPException
    from models.schemas import Settings

    # The harness stubs `storage.get_settings` to a constant (harness.py:19),
    # so the settings round-trip is emulated with a dict the handler really
    # reads and writes — the guard logic is the subject here, not SQLite.
    real_get, real_update = storage.get_settings, storage.update_settings
    stored = {}
    storage.get_settings = lambda: dict(stored)
    storage.update_settings = lambda d: (stored.clear(), stored.update(d))
    _member('Lockable')
    try:
        try:
            _main.update_settings(Settings(auth_enforce=True), BackgroundTasks())
            check(False, "the flip went through while somebody had no way in")
        except HTTPException as e:
            check(e.status_code == 400 and 'Lockable' in str(e.detail),
                  f"the refusal must name who would be locked out: {e.detail}")
        check(not stored.get('auth_enforce'),
              "a refused flip still wrote auth_enforce")
        # Give every active member a way in; the same flip then goes through.
        for m in storage.get_all_members():
            if not m.get('password_hash') and not m.get('pin_hash'):
                storage.set_member_pin(m['id'], '1234')
        _main.update_settings(Settings(auth_enforce=True), BackgroundTasks())
        check(stored.get('auth_enforce') is True,
              "the flip did not stick once everybody had a credential")
        _main.update_settings(Settings(auth_enforce=False), BackgroundTasks())
        check(stored.get('auth_enforce') is False,
              "enforcement could not be turned back OFF — the emergency lever "
              "must never be guarded")
    finally:
        storage.get_settings, storage.update_settings = real_get, real_update


def scenario_z_the_family_listing_answers_only_on_trusted_ground():
    """Decision 4's leak, closed (S8). `/api/members` and `/api/drivers`
    answered ANYONE because the picker needed them before authentication —
    which published every name, email and role to whoever loaded the page.
    The picker only exists on trusted ground now (a vouched device, the LAN,
    ingress); off it the front door is the login page, which needs no list.
    Any resolved tier still answers — a signed-in member reads the family
    from anywhere. Dark until the flip, recorded meanwhile."""
    import main as _main
    from services import auth as _auth
    from fastapi import HTTPException

    class _Req:
        def __init__(self, headers=None, query=None):
            self.headers = headers or {}
            self.query_params = query or {}

    tunnel = {'cf-connecting-ip': '203.0.113.7'}
    orig = _auth.enforcing
    _auth.enforcing = lambda: True
    try:
        for fn, what in ((_main.get_members, 'members'),
                         (_main.get_drivers, 'drivers')):
            try:
                fn(_Req(tunnel))
                check(False, f"the family's {what} were served to the open internet")
            except HTTPException as e:
                check(e.status_code == 401,
                      f"expected 401 on anonymous {what}, got {e.status_code}")
        # The LAN answers — the kitchen tablet's picker must keep working.
        check(isinstance(_main.get_members(_Req({})), list),
              "the LAN lost the picker's member list")
        # A vouched device answers from anywhere (the point of vouching).
        storage.trust_device('z-tablet', 'Test tablet', kind='personal')
        check(isinstance(_main.get_members(
                  _Req({**tunnel, 'x-device-id': 'z-tablet'})), list),
              "a vouched device off the LAN lost the picker")
        # A signed-in member reads the family from anywhere.
        tok = storage.create_member_token(_member('Zed'))
        check(isinstance(_main.get_members(
                  _Req({**tunnel, 'x-member-token': tok})), list),
              "a signed-in member lost the members list")
    finally:
        _auth.enforcing = orig
    # Dark: recorded, never refused — the arc's own discipline.
    check(isinstance(_main.get_members(_Req(tunnel)), list),
          "audit mode refused the members list")
    check(_auth.audit_report()['identity'].get('untrusted-members', 0) >= 1,
          "an untrusted listing read was not recorded while dark")
    # The ground probe is how the PWA picks its front door.
    check(_main.account_ground(_Req(tunnel))['trusted'] is False,
          "the open internet read as trusted ground")
    check(_main.account_ground(_Req({}))['trusted'] is True,
          "the LAN stopped being trusted ground")
    # And the table: the listing GETs answer pre-auth (the handler gates
    # them); every write on those prefixes is still administration.
    check(_auth.resolve('GET', '/api/drivers') == _auth.ANYONE
          and _auth.resolve('GET', '/api/account/ground') == _auth.ANYONE,
          "a picker data source lost its table entry")
    check(_auth.resolve('POST', '/api/drivers') == _auth.PARENTS,
          "the drivers GET carve-out opened driver WRITES")


def scenario_z2_the_install_nudge_speaks_only_to_a_browser_tab():
    """The invite's last step: an invite necessarily lands in a browser tab,
    so the set-password page hands off with ?from=invite and the app offers
    Add-to-Home-Screen. The guards are the feature — shown to the wrong
    surface it is worse than nothing, so each exclusion is pinned:
    a home-screen launch must never be nagged to install itself, the HA
    companion webview cannot Add-to-Home-Screen at all, and installing from
    an ingress path would bake supervisor's rotating token into the icon
    (the same link rot v2.257.2 fixed in mailed invites)."""
    import os
    import main as _main
    base = os.path.dirname(_main.__file__)
    app_src = open(os.path.join(base, 'templates', 'app.html'),
                   encoding='utf-8').read()
    frag = app_src[app_src.index('function installContext'):
                   app_src.index('function dismissInstallNudge')]
    for guard, why in (
            ('display-mode: standalone',
             'a home-screen launch would be nagged to install itself'),
            ('navigator.standalone',
             'older iOS only reports standalone through navigator.standalone'),
            ('Home Assistant',
             'the HA companion webview cannot Add-to-Home-Screen'),
            ('hassio_ingress',
             'an ingress install bakes a rotting supervisor token into the icon')):
        check(guard in frag, f"the install nudge lost its {guard!r} guard — {why}")
    check('beforeinstallprompt' in app_src,
          "Android lost the real Install button (and with it the only "
          "already-installed signal that platform offers)")
    sp = open(os.path.join(base, 'templates', 'set_password.html'),
              encoding='utf-8').read()
    check('../app?from=invite' in sp,
          "the set-password page no longer hands off with ?from=invite, so "
          "the nudge stops being the invite flow's last step")


SCENARIOS = [v for k, v in sorted(globals().items()) if k.startswith("scenario_")]

if __name__ == "__main__":
    for fn in SCENARIOS:
        fn()
        print(f"  ok  {fn.__name__}")
    print(f"\n{len(SCENARIOS)}/{len(SCENARIOS)} account scenarios passed")
